import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import DarkModeToggle from "./components/DarkModeToggle";
import Nav from "./pages/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}

            {/* Dark Mode Toggle */}
            <Nav />
            <DarkModeToggle />


        {children}
      </body>
    </html>
  );
}
